#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service defaults single
PROCESS_NAME="esphome"

check_container_initialized
check_service_initialized init

if [ -n "${ADMIN_USER}" ] && [ -n "${ADMIN_PASS}" ]; then
    _esphome_admin_credentials="--username ${ADMIN_USER} --password ${ADMIN_PASS}"
fi
liftoff

print_start "Starting ESPHome ${ESPHOME_VERSION}"
exec esphome \
                dashboard \
                    --address "${LISTEN_IP}" \
                    --port "${LISTEN_PORT}" \
                    ${_esphome_admin_credentials} "${CONFIG_PATH}"