#!/command/with-contenv bash

source /assets/functions/00-container

prepare_service
PROCESS_NAME="esphome"

bootstrap_filesystem
configure_cache
configure_logging
configure_proxy
configure_settings

liftoff